teste 2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,12 +14,32 @@ jobs:
 
     steps:
     - name: Use Node.js 16
-      uses: actions/setup-node@v2 # Atualizado para a versão correta
+      uses: actions/setup-node@v2
       with:
-        node-version: 16 # Especifica a versão do Node.js
+        node-version: 16
 
     - name: Checkout repository
       uses: actions/checkout@v2
+
+    - name: Install dependencies
+      run: npm ci
+
+    - name: Build
+      run: npm run build
+
+    - name: Test
+      run: npm test
+
+    - name: Check test coverage
+      run: |
+        COVERAGE_THRESHOLD=80
+        COVERAGE=$(npx nyc report --reporter=text-summary | grep 'All files' | awk '{print $4}' | sed 's/%//')
+        if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
+          echo "Error: Test coverage is below $COVERAGE_THRESHOLD%. Coverage: $COVERAGE%"
+          exit 1
+        else
+          echo "Success: Test coverage is above $COVERAGE_THRESHOLD%. Coverage: $COVERAGE%"
+        fi
 
     - name: Set up Python
       uses: actions/setup-python@v2
